import mongoose from 'mongoose';

const locationSchema = mongoose.Schema(
  {
    user: {
      type: mongoose.Schema.Types.ObjectId,
      required: true,
      ref: 'User',
    },
    name: { type: String, required: true },
    image: { type: String, required: true },
    point1: { type: String, required: false },
    point2: { type: String, required: false },
    point3: { type: String, required: false },
    bonusPoint: { type: String, required: false },
    goImage: { type: String, required: false },
    go1h3: { type: String, required: false },
    go1all: { type: String, required: false },
    go1li1: { type: String, required: false },
    go1li2: { type: String, required: false },
    go1li3: { type: String, required: false },
    go1li4: { type: String, required: false },
    go2h3: { type: String, required: false },
    go2all: { type: String, required: false },
    go2li1: { type: String, required: false },
    go2li2: { type: String, required: false },
    go2li3: { type: String, required: false },
    go2li4: { type: String, required: false },
    go3h3: { type: String, required: false },
    go3all: { type: String, required: false },
    go3li1: { type: String, required: false },
    go3li2: { type: String, required: false },
    go3li3: { type: String, required: false },
    go3li4: { type: String, required: false },

    eat1Image: { type: String, required: false },
    eat1name: { type: String, required: false },
    eat1Address: { type: String, required: false },
    eat1Phone: { type: String, required: false },
    eat1Description: { type: String, required: false },
    eat2Image: { type: String, required: false },
    eat2name: { type: String, required: false },
    eat2Address: { type: String, required: false },
    eat2Phone: { type: String, required: false },
    eat2Description: { type: String, required: false },
    eat3Image: { type: String, required: false },
    eat3name: { type: String, required: false },
    eat3Address: { type: String, required: false },
    eat3Phone: { type: String, required: false },
    eat3Description: { type: String, required: false },

    drink1Image: { type: String, required: false },
    drink1name: { type: String, required: false },
    drink1Address: { type: String, required: false },
    drink1Phone: { type: String, required: false },
    drink1Description: { type: String, required: false },
    drink2Image: { type: String, required: false },
    drink2name: { type: String, required: false },
    drink2Address: { type: String, required: false },
    drink2Phone: { type: String, required: false },
    drink2Description: { type: String, required: false },
    drink3Image: { type: String, required: false },
    drink3name: { type: String, required: false },
    drink3Address: { type: String, required: false },
    drink3Phone: { type: String, required: false },
    drink3Description: { type: String, required: false },

    play1Image: { type: String, required: false },
    play1name: { type: String, required: false },
    play1Address: { type: String, required: false },
    play1Phone: { type: String, required: false },
    play1Description: { type: String, required: false },
    play2Image: { type: String, required: false },
    play2name: { type: String, required: false },
    play2Address: { type: String, required: false },
    play2Phone: { type: String, required: false },
    play2Description: { type: String, required: false },
    play3Image: { type: String, required: false },
    play3name: { type: String, required: false },
    play3Address: { type: String, required: false },
    play3Phone: { type: String, required: false },
    play3Description: { type: String, required: false },

    stay1Image: { type: String, required: false },
    stay1name: { type: String, required: false },
    stay1Address: { type: String, required: false },
    stay1url: { type: String, required: false },
    stay1Phone: { type: String, required: false },
    stay1Description: { type: String, required: false },
    stay2Image: { type: String, required: false },
    stay2name: { type: String, required: false },
    stay2Address: { type: String, required: false },
    stay2url: { type: String, required: false },
    stay2Phone: { type: String, required: false },
    stay2Description: { type: String, required: false },
    stay3Image: { type: String, required: false },
    stay3name: { type: String, required: false },
    stay3Address: { type: String, required: false },
    stay3url: { type: String, required: false },
    stay3Phone: { type: String, required: false },
    stay3Description: { type: String, required: false },

    footerImage: { type: String, Required: true },
  },
  {
    timestamps: true,
  }
);

const Location = mongoose.model('Location', locationSchema);

export default Location;
